In [1]:
import numpy as np
X = np.array(
[[73.847017017515, 241.893563180437],
 [68.7819040458903, 162.3104725213],
 [74.1101053917849, 212.7408555565],
 [71.7309784033377, 220.042470303077],
 [69.8817958611153, 206.349800623871],
 [67.2530156878065, 152.212155757083],
 [68.7850812516616, 183.927888604031],
 [68.3485155115879, 167.971110489509],
 [67.018949662883, 175.92944039571],
 [63.4564939783664, 156.399676387112]]
)

In [3]:
X.shape

(10, 2)

In [10]:
X.mean() # mean of all data

128.64956453152894

In [34]:
np.mean(X[:,0]) # mean of Weights

69.32138568119487

In [46]:
np.mean(X[:,1]) # mean of the Heights 

187.97774338186304

In [37]:
X[1,:] 

array([ 68.78190405, 162.31047252])

In [50]:
np.mean(X[:5,1]) # mean height for first 5

208.667432437037

In [51]:
X[:,1] # prints all items in second column

array([241.89356318, 162.31047252, 212.74085556, 220.0424703 ,
       206.34980062, 152.21215576, 183.9278886 , 167.97111049,
       175.9294404 , 156.39967639])

In [59]:
(X[8,0]) #mean of weigth of the 9th subject

67.018949662883

In [ ]:
def sub_mean_correspond(X, i):
    X[i,0] = [X[i[0]] - np.mean(X[:,0]) for i in len(X)]
    X[i,1]
    return num 

In [66]:
X - np.mean(X, axis=0)

array([[  4.52563134,  53.9158198 ],
       [ -0.53948164, -25.66727086],
       [  4.78871971,  24.76311217],
       [  2.40959272,  32.06472692],
       [  0.56041018,  18.37205724],
       [ -2.06836999, -35.76558762],
       [ -0.53630443,  -4.04985478],
       [ -0.97287017, -20.00663289],
       [ -2.30243602, -12.04830299],
       [ -5.8648917 , -31.57806699]])

In [67]:
A = np.array([[1,2], [3, 4]])

In [68]:
np.sum(A) #sum of elements in the array

10

In [69]:
np.sum(A, axis=0) # sum of elements in columns

array([4, 6])

In [70]:
np.sum(A, axis=1) # sum of elements in row 

array([3, 7])

In [71]:
np.product(A)

24

In [79]:
np.divide(A,2)

array([[0.5, 1. ],
       [1.5, 2. ]])

In [82]:
np.blackman(30)

array([-1.38777878e-17,  4.29575572e-03,  1.80031929e-02,  4.33557342e-02,
        8.33642979e-02,  1.40900814e-01,  2.17687257e-01,  3.13399509e-01,
        4.25078745e-01,  5.46989438e-01,  6.70982480e-01,  7.87328859e-01,
        8.85901263e-01,  9.57514031e-01,  9.95198623e-01,  9.95198623e-01,
        9.57514031e-01,  8.85901263e-01,  7.87328859e-01,  6.70982480e-01,
        5.46989438e-01,  4.25078745e-01,  3.13399509e-01,  2.17687257e-01,
        1.40900814e-01,  8.33642979e-02,  4.33557342e-02,  1.80031929e-02,
        4.29575572e-03, -1.38777878e-17])